import type { GameManifest } from '@aprumo/protocol';

export const manifest: GameManifest = {
  appId: 'pequeno-chef',
  version: '2.0.0',
  name: 'Pequeno Chef',
  kind: 'game',
  summary: 'Culinária terapêutica, análise de tarefas e tolerância alimentar: a criança prepara receitas passo a passo, explorando ingredientes e sequências funcionais.',
  clinical: {
    purposes: ['teaching', 'probe', 'reinforcer'],
    models: { ABA: 'trial-based', DENVER: 'joint-routine' },
    repertoires: ['adl', 'imitation', 'play'],
    autoScoring: ['adl', 'play'],
    therapistScoring: [],
    playLevel: 'functional',
    trialUnit: 'Execução de etapa na cadeia da receita culinária.',
    correctResponse: 'Identificação e adição do ingrediente ou utensílio correto para a etapa da receita.',
    minFieldSize: 2,
    maxFieldSize: 4,
    latencyMaxMs: 15000,
    builtInPrompts: [{ code: 'PULSE', afterMs: 8000, intrusiveness: 0.25 }],
    prerequisites: ['tolera-tablet', 'atencao-compartilhada-inicial'],
    ageRangeMonths: [30, 144],
    requiresAdult: false,
    sensory: { flashes: false, motionReducible: true, sound: 'adjustable' },
    emits: [
      'SESSION_STARTED',
      'LEVEL_STARTED',
      'TRIAL_STARTED',
      'STIMULUS_PRESENTED',
      'RESPONSE_STARTED',
      'TRIAL_COMPLETED',
      'PROMPT_USED',
      'REINFORCER_PRESENTED',
      'LEVEL_COMPLETED',
      'REWARD_TRIGGERED',
      'SESSION_PAUSED',
      'SESSION_RESUMED',
      'SESSION_COMPLETED',
      'APP_CLOSED',
    ],
  },
};
