import type { GameManifest } from '@aprumo/protocol';

export const manifest: GameManifest = {
  appId: 'social-city',
  version: '1.0.0',
  name: 'Social City 3D',
  kind: 'game',
  summary: 'Simulação urbana 3D para adolescentes: prática de interações sociais reais em cafeteria, transporte público, conversas em grupo e estabelecimento assertivo de limites.',
  clinical: {
    purposes: ['teaching', 'probe', 'reinforcer'],
    models: { ABA: 'trial-based', DENVER: 'joint-routine' },
    repertoires: ['social', 'play'],
    autoScoring: ['social'],
    therapistScoring: [],
    playLevel: 'reciprocal',
    trialUnit: 'Tomada de decisão em interação social urbana e comunicação assertiva.',
    correctResponse: 'Seleção de resposta assertiva, empática e contextualizada à situação social.',
    minFieldSize: 2,
    maxFieldSize: 4,
    latencyMaxMs: 25000,
    builtInPrompts: [{ code: 'HINT', afterMs: 10000, intrusiveness: 0.25 }],
    prerequisites: ['tolera-tablet', 'cognicao-social-basica'],
    ageRangeMonths: [144, 216],
    requiresAdult: false,
    sensory: { flashes: false, motionReducible: true, sound: 'adjustable' },
    emits: [
      'SESSION_STARTED',
      'LEVEL_STARTED',
      'TRIAL_STARTED',
      'STIMULUS_PRESENTED',
      'RESPONSE_STARTED',
      'TRIAL_COMPLETED',
      'PROMPT_USED',
      'REINFORCER_PRESENTED',
      'LEVEL_COMPLETED',
      'REWARD_TRIGGERED',
      'SESSION_PAUSED',
      'SESSION_RESUMED',
      'SESSION_COMPLETED',
      'APP_CLOSED',
    ],
  },
};
