import type { GameManifest } from '@aprumo/protocol';

export const manifest: GameManifest = {
  appId: 'missao-independencia',
  version: '2.0.0',
  name: 'Missão Independência',
  kind: 'game',
  summary: 'Autonomia da vida real e funções executivas: missões de arrumar a mochila escolar, fazer compras e conferir troco no mercadinho, navegar itinerário de transporte público e rotina de saída.',
  clinical: {
    purposes: ['teaching', 'probe', 'reinforcer'],
    models: { ABA: 'trial-based', DENVER: 'joint-routine' },
    repertoires: ['adl', 'play'],
    autoScoring: ['adl'],
    therapistScoring: [],
    playLevel: 'functional',
    trialUnit: 'Execução de passo na cadeia de autonomia ou AVD.',
    correctResponse: 'Identificação da ação, item ou decisão correta para a etapa da missão.',
    minFieldSize: 2,
    maxFieldSize: 4,
    latencyMaxMs: 15000,
    builtInPrompts: [{ code: 'PULSE', afterMs: 8000, intrusiveness: 0.25 }],
    prerequisites: ['tolera-tablet', 'atencao-compartilhada-inicial'],
    ageRangeMonths: [48, 192],
    requiresAdult: false,
    sensory: { flashes: false, motionReducible: true, sound: 'adjustable' },
    emits: [
      'SESSION_STARTED',
      'LEVEL_STARTED',
      'TRIAL_STARTED',
      'STIMULUS_PRESENTED',
      'RESPONSE_STARTED',
      'TRIAL_COMPLETED',
      'PROMPT_USED',
      'REINFORCER_PRESENTED',
      'LEVEL_COMPLETED',
      'REWARD_TRIGGERED',
      'SESSION_PAUSED',
      'SESSION_RESUMED',
      'SESSION_COMPLETED',
      'APP_CLOSED',
    ],
  },
};
